### ISSUE TITLE
ags installation page docs are giving 404

### ISSUE THREAD

**Issue by EpixMan** [Aylur/ags-docs#6]
By going to https://aylur.github.io/ags-docs/ then press "Get Started", it will drive me to:
https://aylur.github.io/ags-docs/config/installation/
I think it should be: 
https://aylur.github.io/ags-docs/config/installation.html
 
Thanks for the great tool and docs!

**Comment by ehanahamed** [comment]
Also, theres a few more links that are wrong:
- the link in the top left corner, of every page "AGS Wiki", leads to `ags-docs.html` instead of `ags-docs/`
- a link on the installation page, "Home Manager module", leads to `home-manager.html` instead of `config/home-manager`
- all the links under "Builtin Widgets" lead to `config/widgets#link.html` instead of `config/widgets#link`
  - Window
  - Box
  - Button
  - CenterBox
  - CircularProgress
  - Entry
  - EventBox
  - Icon
  - Label
  - Overlay
  - ProgressBar
  - Revealer
  - Scrollable
  - Slider
  - Stack
  - Menu
  - MenuItem

I fixed all of these in #7,
If there's anything else that's not listed here and not indirectly fixed by #7, add it below ig
